function createfigure(zdata1, zdata2, zdata3)
%CREATEFIGURE(zdata1, zdata2, zdata3)
%  ZDATA1:  surface zdata
%  ZDATA2:  contour z
%  ZDATA3:  contour z

%  Auto-generated by MATLAB on 08-Apr-2022 20:28:13

% Create figure
figure;

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create surf
surf(zdata1,'FaceAlpha',0.7,'EdgeColor','none');

% Create contour
contour(zdata2,'LineWidth',2,...
    'LevelList',[0.375846437771984 0.386852782107219 0.397859126442454 0.408865470777689]);

% Create contour
contour(zdata3,'LineWidth',2,'LineColor',[1 0 0],'LevelList',[0.5 1 50]);

% Create ylabel
ylabel('Height (Mm)','FontWeight','bold');

% Create xlabel
xlabel('Time (seconds)','FontWeight','bold');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 600]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 45]);
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'CLim',[-3 3],'FontSize',22,'FontWeight','bold','YTickLabel',...
    {'0.06','0.30','0.53','0.77','1.00','1.23','1.47','1.70','1.94','2.17'});
% Create colorbar
colorbar(axes1);

